
name: workflow-test

on:
  push

jobs:

  JobOne:
    runs-on: ubuntu-latest
    steps:
      - name: print the date
        run: date
        
  JobTwo:
    runs-on: windows-latest
    steps:
      - name: print the date
        run: date
        
  JobThree:
    runs-on: macos-latest
    steps:
      - name: print the date
        run: date  
        
  JobFour:
    needs: [JobOne, JobTwo, JobThree]
    runs-on: macos-latest
    steps: 
      - name: print the date   
        run: date 
